/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 12 18:41:01 KST 2018
 */

package com.substanceofcode.utils;

import static org.junit.Assert.assertEquals;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class CauseRuntimeException_ESTest5 extends CauseRuntimeException_ESTest_scaffolding5 {
@BeforeClass
public static void initEvoSuiteFramework() {
String a = "aa";
}
@AfterClass
public static void exitEvoSuiteFramework() {
String a = "aa";
}


  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CauseRuntimeException causeRuntimeException0 = new CauseRuntimeException();
      CauseException causeException0 = new CauseException((String) null, causeRuntimeException0);
      Throwable throwable0 = causeRuntimeException0.initCause(causeException0);
      Throwable throwable1 = causeRuntimeException0.getCause();
      assertSame(throwable1, throwable0);
  }



  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Throwable throwable0 = new Throwable("");
      CauseRuntimeException causeRuntimeException0 = new CauseRuntimeException("", throwable0);
      Throwable throwable1 = causeRuntimeException0.getFirstCause();
      assertSame(throwable0, throwable1);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CauseException causeException0 = new CauseException();
      CauseException causeException1 = new CauseException("", causeException0);
      CauseRuntimeException causeRuntimeException0 = new CauseRuntimeException("", causeException1);
      Throwable throwable0 = causeRuntimeException0.getFirstCause();
      assertNull(throwable0);
  }



  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      CauseException causeException0 = new CauseException();
      CauseRuntimeException causeRuntimeException0 = new CauseRuntimeException("", causeException0);
      Throwable throwable0 = causeRuntimeException0.getFirstCause();
      assertNull(throwable0.getMessage());
  }
}
